version: '3.7'

services:
  broadcaster:
    container_name: ws_endpoint
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /var/lighthouse:/data/
    ports:
      - "${BROADCASTER_PORT}:80"
